[package]
name = "katsu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
fehler = "1.0"
sailfish = "0.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.4", default_features = false, features = ["http1"] }
diesel = { version = "1.4", default_features = false, features = ["sqlite"] }
